### ISSUE TITLE
I'm hungry 

### ISSUE THREAD

**Issue by petrroll** [zouharvi/cfm#1]
Version: Petr 24.8
Repro: Wake up, don't have breakfast, go to work

pls fix

**Comment by zouharvi** [comment]
Assuming you meet all of the prerequisites for complaining:

1. It is a work day
2. It is around noon
3. You are located in the building of MFF at Malá strana

it shouldn't be difficult for you to accept my sincere apologies in the form of a premium free lunch today. Make sure to stop by _today_ before lunch at the 4th floor and you'll get your reward. :slightly_smiling_face:
